// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbb5gmw7YqP0PZaYEjKlCTwd46BkCn9kA',
    appId: '1:249924322303:web:5786421c9ac58a0a729dca',
    messagingSenderId: '249924322303',
    projectId: 'fittrack-app-69bf3',
    authDomain: 'fittrack-app-69bf3.firebaseapp.com',
    storageBucket: 'fittrack-app-69bf3.firebasestorage.app',
    measurementId: 'G-CYXLE7RJM4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUibgEg_b1tkN63dvPYczf0s0jHWv0paM',
    appId: '1:249924322303:android:3041c519540a9a70729dca',
    messagingSenderId: '249924322303',
    projectId: 'fittrack-app-69bf3',
    storageBucket: 'fittrack-app-69bf3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEA0z9uo2_mZkno5n01eCsgBe9DTikqJI',
    appId: '1:249924322303:ios:2e28ae80c48c94e4729dca',
    messagingSenderId: '249924322303',
    projectId: 'fittrack-app-69bf3',
    storageBucket: 'fittrack-app-69bf3.firebasestorage.app',
    iosClientId: '249924322303-1efhde33shb191e44l4sksbm7fl8sic1.apps.googleusercontent.com',
    iosBundleId: 'com.example.fitnessTrackerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEA0z9uo2_mZkno5n01eCsgBe9DTikqJI',
    appId: '1:249924322303:ios:2e28ae80c48c94e4729dca',
    messagingSenderId: '249924322303',
    projectId: 'fittrack-app-69bf3',
    storageBucket: 'fittrack-app-69bf3.firebasestorage.app',
    iosClientId: '249924322303-1efhde33shb191e44l4sksbm7fl8sic1.apps.googleusercontent.com',
    iosBundleId: 'com.example.fitnessTrackerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCbb5gmw7YqP0PZaYEjKlCTwd46BkCn9kA',
    appId: '1:249924322303:web:070f0a0b00ccd4e5729dca',
    messagingSenderId: '249924322303',
    projectId: 'fittrack-app-69bf3',
    authDomain: 'fittrack-app-69bf3.firebaseapp.com',
    storageBucket: 'fittrack-app-69bf3.firebasestorage.app',
    measurementId: 'G-19L8V9RKGY',
  );
}
